eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #注册服务地址
spring:
  application:
    name: index-data-service  #服务的名称
  zipkin:
    base-url: http://localhost:9411 #链路追踪
    
    