eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-zuul-service
  zipkin:
    base-url: http://localhost:9411 #服务链路追踪
zuul:  #分配网关
  routes:  #所有的访问 /api-codes/ 的请求，都会自动转到 INDEX-CODES-SERVICE 去。
    api-a:  # 而 INDEX-CODES-SERVICE 有3个，就会在这3个之间来回切换。
      path: /api-codes/**
      serviceId: INDEX-CODES-SERVICE
    api-b:   #用网关调用回测数据
      path: /api-backtest/** #访问/api-backtest/**的请求自动转到TREND-TRADING-BACKTEST-SERVICE
      serviceId: TREND-TRADING-BACKTEST-SERVICE
    api-c:
      path: /api-view/**
      serviceId: TREND-TRADING-BACKTEST-VIEW

